### ISSUE TITLE
Possible to remove lxml dependency?

### ISSUE THREAD

**Issue by benmoran56** [sde1000/python-wayland#1]
First of all, fantastic project.  I was just wondering if it would be practical to remove the lxml dependency, and replace it with the standard library's xml module? I'm not sure if xml does DTD validation, so the answer could be "no" without additional work. I was just thinking it would be better if this module could be used without external modules. Cffi also falls in this category, but I suppose your XKB bindings could be rewritten with ctypes if desired.

**Comment by sde1000** [comment]
Yes, I think that should be fairly easy.  If validation against the DTD was removed I'd want to add a bit more code checking for unexpected things in the protocol file.

The XKB bindings really ought to be in a separate project — I'm a bit surprised to find one doesn't already exist.  I only included them here so that the example code would run.

**Comment by benmoran56** [comment]
Yes, the DTD validation is definitely good to have. I was just thinking that it would be nice to reduce the external dependencies if possible, to make it easier for other projects to use python-wayland. 

Having the XKB bindings in a separate project would be nice. I've only been able to find a few random bits of code around, but not a proper library.

**Comment by sde1000** [comment]
Done!  https://github.com/sde1000/python-xkbcommon now exists, and I've removed the lxml dependency.

**Comment by benmoran56** [comment]
Great! This should make it a lot easier to use in standalone projects.

**Comment by AraHaan** [comment]
@sde1000 can you post the link to the commit/pr you opened/made to remove it so I can remove it from one of my libraries too (if possible).

**Comment by sde1000** [comment]
It is commit a15a36b29decfd3a763899693280afc368f56811 that removes the lxml dependency; look at the changes in `wayland/protocol.py`
